name: Publish to Maven Central
on:
  push: 
    tags: 
      - "v*.*.*"
jobs:
  maven-publish:
   runs-on: ubuntu-latest
   steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Install Java and Maven
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Release Maven package
      uses: samuelmeuli/action-maven-publish@v1
      with:
        maven_profiles: 'release-github'
        maven_goals_phases: 'clean deploy'
        maven_args: '-DskipTests'
        gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE_KEY }}
        nexus_username: ${{ secrets.OSSRH_USERNAME }}
        nexus_password: ${{ secrets.OSSRH_TOKEN }}

